from typing import Tuple, Optional, Union, overload

from . import io
from .pycaffe import Net, SGDSolver, NesterovSolver, AdaDeltaSolver
from .pycaffe import RMSPropSolver, AdaDeltaSolver, NCCL, Timer
from .proto.caffe_pb2 import TRAIN, TEST
from .classifier import Classifier
from .detector import Detector
from .net_spec import layers, params, NetSpec, to_proto

# -------------help(caffe)-----------------
__version__ = '1.0.0'

# FUNCTIONS
def has_nccl() -> bool: ...

def init_log(arg1: Optional[int]=None, arg2: Optional[bool]=None) -> None: ...

# print(list(caffe.layer_type_list()))
def layer_type_list() -> caffe.StringVec: ...

def log(info : str) -> None: ...

def set_device(device_id: int) -> None: ...

def set_mode_cpu() -> None: ...

def set_mode_gpu() -> None: ...

def set_multiprocess(val: bool) -> None: ...

def set_random_seed(seed: int) -> None:  ...

def set_solver_count(val: int) -> None: ...

def set_solver_rank(val: int) -> None: ...

def solver_count() -> int: ...

def solver_rank() -> int: ...

# ..........................................